### PR TITLE
Hello! I have fixed the blocked login button in the largest font and display size.

### PR DESCRIPTION
**Pull request by EasyVector**
Dear developer:

I am the creator of issue #6, and I have fixed the blocked login button in the largest font and display size. It looks like the screenshot below. I would appreciate it if you could kindly revise my code and give me some advice. Thank you so much for your precious time.  :)

Here is the screenshot. This page is scrollable now, so I believe this problem is solved now.

copy

### CODE REVIEW

**Comment by EasyVector** [comment]
Hello! By the way, I just spotted another display problem on the token login page in the same display configurations. The screenshot is like this, and the login button is blocked like the former:

copy

I have just fixed this problem, and I will commit this code later.

Here is the screenshot after my fix:

copy

**Comment by deftk** [comment]
Hey, thanks for reporting this issue and providing a solution by yourself! I have to admit I didn't think of this kind of issue at first and after a bit of testing the problem seems to be a bit more complex beside these login screens. Also images and the header of the navigation drawer and so on are affected by this issue.

I think the way-to-go should consider scaling (e.g. size of the headline and space between the components) instead of making everything scrollable, because that won't work for the other problems.

Feel free to try and solve this issue for the login screens by yourself if you would like to. I think it can be done by basically using "dp" instead of "sp" (or the other way around, depending on the context) for measurement units inside the layout xml, see https://developer.android.com/guide/topics/resources/more-resources.html#Dimension.

Now I would try to solve the other issues regarding large fonts and if you would like to you could also try to solve those with the login screens. If you don't want that I can do that too.

Thanks again for helping and thanks for using my app!

**Comment by EasyVector** [comment]
Thank you so much! Indeed, this kind of issue is easy to be overlooked, and that is the reason why I am doing this. I am always trying to find a better way to cope with these issues, especially the blocked ones. I would like to keep on following your project and do what I could to make it better :) 
Also, I am considering the choice of using dp or sp. sp is good for text scaling, but sometimes other issues might come along with it.... It depends on many factors.

**Comment by deftk** [comment]
I think https://github.com/deftkHD/OpenWebWeaver-Android/commit/2bf4742934b7c86d66e1e3b23e1a3584828fb155 (dev branch) should fix most of the issues regarding (text-)scaling. Maybe you can take a look and notify me if anything doesn't work or scale properly. Thanks for helping in order to create more accessible apps :)

**Comment by EasyVector** [comment]
OK, I will take a look later. 👍

**Comment by deftk** [comment]
Since there is no update on this topic, I will count this as closed. You can reopen your issue if there still appear any problems

**Comment by EasyVector** [comment]
Hello! Sorry for the late. I did some study on your update and I found that you changed the text size from sp to dp on the login page which could alleviate the growing size of texts. I can not agree with you more and I support this modification. 👍

**Pull request closed without merging**
